"""
crear un SCRIPT en Python que cuente la cantidad de vocales en una frase ingresada por el usuario. 
"""

#from DIA1.FUNCIONES import contar_vocales
    

#frase_usuario= input("Ingresa una Frase:")
#cantidad_vocales = contar_vocales(frase_usuario)
#print(f"La Frase contiene {cantidad_vocales} vocales")


numeros = [1,2,3,4,5]
for numero in numeros:
    if numero==6:
        print("Numero encontrado")
        break
else:
    print("Numero no encontrado")



